apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: wiki.hanapoulpe.org
  name: wiki-js
  namespace: wiki
  workload.user.cattle.io/workloadselector: apps.deployment-wiki-wiki-js
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-wiki-wiki-js
  replicas: 1
  template:
    metadata:
      labels:
        app: wiki.hanapoulpe.org
        workload.user.cattle.io/workloadselector: apps.deployment-wiki-wiki-js
    spec:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-wiki-wiki-js
      containers:
        - envFrom:
            - secretRef:
                name: wiki-db-secret
                optional:
                  false
          #env:
            #- name: SSL_ACTIVE
            #  value: "true"
            #- name: LETSENCRYPT_DOMAIN
            #  value: wikijdr.hanapoulpe.org
            #- name: LETSENCRYPT_EMAIL
            #  value: hana@hanapoulpe.org
            - name: HA_ACTIVE
              value: "1"
          image: requarks/wiki
          imagePullPolicy: Always
          name: wiki-js
          ports:
            - containerPort: 3000
              name: wiki-http
              protocol: TCP
            - containerPort: 3443
              name: wiki-https
              protocol: TCP
      restartPolicy: Always
